"""baseline

Revision ID: 0001
Revises:
Create Date: 2026-08-30 13:32:40.471534

"""

from __future__ import annotations

import sqlalchemy as sa
from collections.abc import Sequence

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "design_systems",
        sa.Column(
            "id",
            sa.String(length=26),
            nullable=False,
            comment="ULID primary key",
        ),
        sa.Column(
            "slug",
            sa.String(length=256),
            nullable=False,
            comment="Unique slug identifier (e.g. default)",
        ),
        sa.Column("title", sa.Text(), nullable=False, comment="Front matter name"),
        sa.Column(
            "description", sa.Text(), nullable=True, comment="Front matter description"
        ),
        sa.Column(
            "spec_version",
            sa.String(length=256),
            nullable=True,
            comment="Front matter version",
        ),
        sa.Column(
            "derived_from_id",
            sa.String(length=26),
            nullable=True,
            comment="Provenance of a derived system",
        ),
        sa.Column(
            "front_matter_extras",
            sa.JSON(),
            nullable=False,
            comment="Unmodeled front matter keys preserved verbatim",
        ),
        sa.Column(
            "front_matter_raw",
            sa.Text(),
            nullable=False,
            comment="Raw front matter text",
        ),
        sa.Column(
            "guide_markdown",
            sa.Text(),
            nullable=False,
            comment="DESIGN.md body without front matter",
        ),
        sa.Column(
            "source_path",
            sa.String(length=1024),
            nullable=True,
            comment="Linked DESIGN.md path; NULL = DB-only",
        ),
        sa.Column(
            "source_root",
            sa.String(length=1024),
            nullable=True,
            comment="Absolute repo root at index time; source_path is relative to it",
        ),
        sa.Column(
            "source_digest",
            sa.String(length=256),
            nullable=True,
            comment="sha256 digest at last sync",
        ),
        sa.Column(
            "source_mtime_ns",
            sa.BigInteger(),
            nullable=True,
            comment="Source file mtime in nanoseconds",
        ),
        sa.Column(
            "source_size",
            sa.Integer(),
            nullable=True,
            comment="Source file size in bytes",
        ),
        sa.Column(
            "synced_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Last file sync time",
        ),
        sa.Column(
            "created_time",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Created time",
        ),
        sa.Column(
            "updated_time",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Updated time",
        ),
        sa.Column(
            "deleted",
            sa.BigInteger(),
            server_default="0",
            nullable=False,
            comment="Logical delete flag (0: No, primary key ID: Yes)",
        ),
        sa.Column(
            "deleted_time",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Deleted time",
        ),
        sa.ForeignKeyConstraint(
            ["derived_from_id"],
            ["design_systems.id"],
            name=op.f("fk_design_systems_derived_from_id_design_systems"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_design_systems")),
        sa.UniqueConstraint("slug", name="uq_design_systems_slug"),
        comment="Design systems",
    )
    op.create_table(
        "design_tokens",
        sa.Column(
            "id",
            sa.String(length=26),
            nullable=False,
            comment="ULID primary key; re-issued on every token sync. Stable identity is (design_system_id, token_path); never reference as a FK",
        ),
        sa.Column(
            "design_system_id",
            sa.String(length=26),
            nullable=False,
            comment="Owning design system",
        ),
        sa.Column(
            "tier",
            sa.String(length=64),
            nullable=False,
            comment="foundation | component",
        ),
        sa.Column(
            "token_path",
            sa.String(length=512),
            nullable=False,
            comment="e.g. colors.primary",
        ),
        sa.Column(
            "value",
            sa.Text(),
            nullable=False,
            comment="Token value or reference expression",
        ),
        sa.Column(
            "origin",
            sa.String(length=64),
            nullable=False,
            comment="design_md | admin_ui | agent",
        ),
        sa.Column(
            "created_time",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Created time",
        ),
        sa.Column(
            "updated_time",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Updated time",
        ),
        sa.Column(
            "deleted",
            sa.BigInteger(),
            server_default="0",
            nullable=False,
            comment="Logical delete flag (0: No, primary key ID: Yes)",
        ),
        sa.Column(
            "deleted_time",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Deleted time",
        ),
        sa.CheckConstraint(
            "origin IN ('design_md', 'admin_ui', 'agent')",
            name=op.f("ck_design_tokens_origin"),
        ),
        sa.CheckConstraint(
            "tier IN ('foundation', 'component')", name=op.f("ck_design_tokens_tier")
        ),
        sa.ForeignKeyConstraint(
            ["design_system_id"],
            ["design_systems.id"],
            name=op.f("fk_design_tokens_design_system_id_design_systems"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_design_tokens")),
        sa.UniqueConstraint(
            "design_system_id", "token_path", name="uq_design_tokens_ds_path"
        ),
        comment="Normalized design tokens",
    )
    with op.batch_alter_table("design_tokens", schema=None) as batch_op:
        batch_op.create_index(
            "ix_design_tokens_ds_tier", ["design_system_id", "tier"], unique=False
        )

    op.create_table(
        "prototype_runs",
        sa.Column(
            "id",
            sa.String(length=26),
            nullable=False,
            comment="ULID primary key",
        ),
        sa.Column(
            "design_system_id",
            sa.String(length=26),
            nullable=False,
            comment="Associated design system ID",
        ),
        sa.Column("screen_goal", sa.Text(), nullable=False, comment="Goal of this run"),
        sa.Column(
            "layout_preset",
            sa.String(length=128),
            nullable=False,
            comment="Layout preset identifier (e.g. split-card)",
        ),
        sa.Column(
            "token_snapshot",
            sa.JSON(),
            nullable=False,
            comment="Resolved token flat map at run creation",
        ),
        sa.Column(
            "variation_axes",
            sa.JSON(),
            nullable=False,
            comment="Varied token paths",
        ),
        sa.Column(
            "status",
            sa.String(length=64),
            nullable=False,
            comment="active | exported | archived",
        ),
        sa.Column(
            "created_time",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Created time",
        ),
        sa.Column(
            "updated_time",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Updated time",
        ),
        sa.Column(
            "deleted",
            sa.BigInteger(),
            server_default="0",
            nullable=False,
            comment="Logical delete flag (0: No, primary key ID: Yes)",
        ),
        sa.Column(
            "deleted_time",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Deleted time",
        ),
        sa.CheckConstraint(
            "status IN ('active', 'exported', 'archived')",
            name=op.f("ck_prototype_runs_status"),
        ),
        sa.ForeignKeyConstraint(
            ["design_system_id"],
            ["design_systems.id"],
            name=op.f("fk_prototype_runs_design_system_id_design_systems"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prototype_runs")),
        comment="Prototype runs",
    )
    with op.batch_alter_table("prototype_runs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_prototype_runs_ds_created",
            ["design_system_id", "created_time"],
            unique=False,
        )

    op.create_table(
        "candidates",
        sa.Column(
            "run_id",
            sa.String(length=26),
            nullable=False,
            comment="Parent run ID",
        ),
        sa.Column(
            "candidate_key",
            sa.String(length=64),
            nullable=False,
            comment="Candidate key (e.g. c1, c2)",
        ),
        sa.Column("label", sa.Text(), nullable=False, comment="Display label"),
        sa.Column("position", sa.Integer(), nullable=False, comment="Display order"),
        sa.Column(
            "initial_tokens",
            sa.JSON(),
            nullable=False,
            comment="Initial token values at creation",
        ),
        sa.Column(
            "token_overrides",
            sa.JSON(),
            nullable=False,
            comment="Effective token overrides",
        ),
        sa.Column(
            "snapshot_path",
            sa.String(length=1024),
            nullable=True,
            comment="Snapshot image file path",
        ),
        sa.Column(
            "created_time",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Created time",
        ),
        sa.Column(
            "updated_time",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Updated time",
        ),
        sa.Column(
            "deleted",
            sa.BigInteger(),
            server_default="0",
            nullable=False,
            comment="Logical delete flag (0: No, primary key ID: Yes)",
        ),
        sa.Column(
            "deleted_time",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Deleted time",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["prototype_runs.id"],
            name=op.f("fk_candidates_run_id_prototype_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("run_id", "candidate_key", name=op.f("pk_candidates")),
        comment="Candidates per prototype run",
    )
    op.create_table(
        "exports",
        sa.Column(
            "id",
            sa.String(length=26),
            nullable=False,
            comment="ULID primary key",
        ),
        sa.Column(
            "run_id",
            sa.String(length=26),
            nullable=False,
            comment="Parent run ID",
        ),
        sa.Column(
            "candidate_key",
            sa.String(length=64),
            nullable=False,
            comment="Exported candidate key",
        ),
        sa.Column(
            "format", sa.String(length=64), nullable=False, comment="Export format"
        ),
        sa.Column(
            "output_path",
            sa.String(length=1024),
            nullable=True,
            comment="Written file path, if any",
        ),
        sa.Column(
            "byte_size",
            sa.Integer(),
            nullable=True,
            comment="Emitted payload size in bytes",
        ),
        sa.Column(
            "created_time",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Created time",
        ),
        sa.Column(
            "updated_time",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Updated time",
        ),
        sa.Column(
            "deleted",
            sa.BigInteger(),
            server_default="0",
            nullable=False,
            comment="Logical delete flag (0: No, primary key ID: Yes)",
        ),
        sa.Column(
            "deleted_time",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Deleted time",
        ),
        sa.CheckConstraint(
            "format IN ('react-tailwind', 'vue-tailwind', 'html-css', 'json-tokens')",
            name=op.f("ck_exports_format"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id", "candidate_key"],
            ["candidates.run_id", "candidates.candidate_key"],
            name=op.f("fk_exports_run_id_candidates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exports")),
        comment="Export records per candidate",
    )
    op.create_table(
        "slot_contents",
        sa.Column(
            "run_id",
            sa.String(length=26),
            nullable=False,
            comment="Parent run ID",
        ),
        sa.Column(
            "candidate_key",
            sa.String(length=64),
            nullable=False,
            comment="Target candidate key",
        ),
        sa.Column(
            "slot_key",
            sa.String(length=256),
            nullable=False,
            comment="Slot key (e.g. headline, cta-label)",
        ),
        sa.Column("content", sa.Text(), nullable=False, comment="Slot body content"),
        sa.Column(
            "content_kind",
            sa.String(length=64),
            nullable=False,
            comment="text | html | markdown",
        ),
        sa.Column(
            "created_time",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Created time",
        ),
        sa.Column(
            "updated_time",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Updated time",
        ),
        sa.Column(
            "deleted",
            sa.BigInteger(),
            server_default="0",
            nullable=False,
            comment="Logical delete flag (0: No, primary key ID: Yes)",
        ),
        sa.Column(
            "deleted_time",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Deleted time",
        ),
        sa.CheckConstraint(
            "content_kind IN ('text', 'html', 'markdown')",
            name=op.f("ck_slot_contents_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id", "candidate_key"],
            ["candidates.run_id", "candidates.candidate_key"],
            name=op.f("fk_slot_contents_run_id_candidates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "run_id", "candidate_key", "slot_key", name=op.f("pk_slot_contents")
        ),
        comment="Custom slot contents",
    )
    op.create_table(
        "token_patches",
        sa.Column(
            "seq",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Sequential patch order",
        ),
        sa.Column(
            "run_id",
            sa.String(length=26),
            nullable=False,
            comment="Parent run ID",
        ),
        sa.Column(
            "candidate_key",
            sa.String(length=64),
            nullable=False,
            comment="Target candidate key",
        ),
        sa.Column(
            "token_path",
            sa.String(length=512),
            nullable=False,
            comment="Patched token path",
        ),
        sa.Column(
            "origin", sa.String(length=64), nullable=False, comment="agent | admin_ui"
        ),
        sa.Column("next_value", sa.Text(), nullable=False, comment="Value after patch"),
        sa.Column(
            "previous_value",
            sa.Text(),
            nullable=True,
            comment="Value before patch (None if newly added)",
        ),
        sa.Column(
            "created_time",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Created time",
        ),
        sa.Column(
            "updated_time",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Updated time",
        ),
        sa.Column(
            "deleted",
            sa.BigInteger(),
            server_default="0",
            nullable=False,
            comment="Logical delete flag (0: No, primary key ID: Yes)",
        ),
        sa.Column(
            "deleted_time",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Deleted time",
        ),
        sa.CheckConstraint(
            "origin IN ('agent', 'admin_ui')", name=op.f("ck_token_patches_origin")
        ),
        sa.ForeignKeyConstraint(
            ["run_id", "candidate_key"],
            ["candidates.run_id", "candidates.candidate_key"],
            name=op.f("fk_token_patches_run_id_candidates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("seq", name=op.f("pk_token_patches")),
        comment="Token patch history",
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("token_patches", schema=None) as batch_op:
        batch_op.create_index(
            "ix_token_patches_target", ["run_id", "candidate_key", "seq"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("token_patches", schema=None) as batch_op:
        batch_op.drop_index("ix_token_patches_target")

    op.drop_table("token_patches")
    op.drop_table("slot_contents")
    op.drop_table("exports")
    op.drop_table("candidates")
    with op.batch_alter_table("prototype_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_prototype_runs_ds_created")

    op.drop_table("prototype_runs")
    with op.batch_alter_table("design_tokens", schema=None) as batch_op:
        batch_op.drop_index("ix_design_tokens_ds_tier")

    op.drop_table("design_tokens")
    op.drop_table("design_systems")
    # ### end Alembic commands ###
